### ISSUE TITLE
How to get a initial kmer model

### ISSUE THREAD

**Issue by Ballad** [nanoporetech/kmer_models#10]

**Comment by Ballad** [comment]
Hi, How to get the first version of the model without basecall data？

**Comment by fbrennen** [comment]
Hi @Ballad -- unfortunately, kmer models are no longer something we support (and we never supported training them without basecall data anyways -- it's a somewhat involved process). If you want to train a basecall model from nothing then I would suggest having a look at Taiyaki's ab initio training [here](https://github.com/nanoporetech/taiyaki#abinitio-training). That should put you in a position to train further models using Taiyaki or [Bonito](https://github.com/nanoporetech/bonito#training-your-own-model). You can also always come and ask questions in the [Oxford Nanopore Community](https://community.nanoporetech.com/).
