### ISSUE TITLE
r9.4_250bps_180mV models

### ISSUE THREAD

**Issue by poldach** [nanoporetech/kmer_models#3]
My lab has generated several datasets recently using 2D reads on r9.4 run at 250 bp. Metrichor appears to be using models template_r94_e7_250bps_180mV_5mer_nn.jsn and complement_r94_e7_250bps_180mV_5mer_nn.jsn from what we can see in the fast5 files, however these don't appear to be publicly available. For further analysis (e.g. with nanopolish), we would like to be able to access the r9.4_250 bps models if possible, but alternatively would like to know whether  using the r9.2 250bps models can be used with equivalent data from an r9.4 pore?

Thank you!

**Comment by fbrennen** [comment]
If you'd like to see the models used in Metrichor then you can find them as part of the albacore standalone basecaller which is available [here](https://community.nanoporetech.com/posts/albacore-v0-7-offline-base). However, those models are neural network ones, and for nanopolish you're going to want a hidden Markov model (which is what's available in this repository).

The r9.2 250bps models here should be fine for use with nanopolish on r9.4 data run at 250bps -- there is not a large enough difference between the r9.2 and r9.4 pores for you to need a different one as long as the speed stays the same.

**Comment by poldach** [comment]
That is great to hear, thank you!
