### ISSUE TITLE
Direct RNA models

### ISSUE THREAD

**Issue by jts** [nanoporetech/kmer_models#4]
Hi,

Now that direct RNA data sets are starting to appear, will you be able to provide RNA k-mer models?

Thanks

**Comment by fbrennen** [comment]
Here ya go. A couple of notes:

* This is only a 5mer model (as that's all that comes out of our RNN anyways).
* We have uracil labelled as thymine, as that's how the kmers are labelled in the event table in basecalled fast5 files. We'll try and get things updated to use proper labeling later, but this seemed like the most logical approach for the moment.

**Comment by jts** [comment]
Great, thanks for getting this out so quickly!
