### ISSUE TITLE
RNA model standard deviation

### ISSUE THREAD

**Issue by jts** [nanoporetech/kmer_models#6]
Hi,

I noticed that many RNA 5-mers have large standard deviation (113 have stdv >10pA). Is this intrinsic to direct RNA sequencing or a model issue? If the latter, could we get an updated model?

Jared

**Comment by fbrennen** [comment]
Hi @jts -- it's partially an RNA thing, and is exacerbated by the fact that this model was produced relatively early in the development of the direct RNA kit. We unfortunately don't currently have a better alternative, but the next time we train an RNA model we'll look at updating this.

**Comment by jts** [comment]
Hi @fbrennen,

Any update on this? It would be great to get a new RNA model if possible.

Jared

**Comment by fbrennen** [comment]
Hi @jts -- we're in the process of getting an updated RNA condition ready, and we'll put up a new model as soon as that's released (should be pretty soon).

**Comment by jts** [comment]
Great, thanks.

**Comment by fbrennen** [comment]
Hi @jts -- I've pushed a new model. It's marked as an r9.4 model but it will work on either r9.4 or r9.5. We should have the corresponding RNN available in all our usual basecallers in the next week or so.

**Comment by jts** [comment]
Great, thanks Forrest!
