### ISSUE TITLE
mean-std range

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/kmer_models#8]
Hi:
"level_mean: the mean of a Gaussian distribution representing the current observed for this kmer."
In the model file r9.4_180mv_450bps_6mer, the raw signals range from 400 to 500, but the level_means range from 70 to 100. What kind of scaling transformation is made on the raw signal data.
Thanks
Neng

**Comment by fbrennen** [comment]
HI @huangnengCSU -- to convert from the ADC values that are stored in your fast5 Raw section you need to scale them using the range, offset, and digitisation values appropriate to that channel. Check out some sample code in the ont_fast5_api project here: 

https://github.com/nanoporetech/ont_fast5_api/blob/4d5691645ce2d5e326f6dfa7ef28bc4c3b9bc903/ont_fast5_api/fast5_file.py#L682
