### ISSUE TITLE
raw fast5 quality control

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/kmer_models#9]
Hi:
I am doing some research using raw signals in fast5, but there are some obviously low quality sequencing signals. I want to know is there some strategy to filter fast5 files without basecalling.

**Comment by fbrennen** [comment]
Hi @huangnengCSU -- there might be a few things you could try, though basecalling is fairly quick if you've got a reasonable GPU and is likely to be the easiest approach. I would recommend posting your question in the Nanopore Community and asking there for suggestions.
